### ISSUE TITLE
Magnifier is cut off

### ISSUE THREAD

**Issue by Toraih** [i-net-software/dokuwiki-plugin-magnifier#2]
![wiki-magifier](https://user-images.githubusercontent.com/4192623/43070131-4afeb0a0-8e6f-11e8-81b4-ebde083ddf81.png)

The Magnifier is cut off on the left side, is there a know problem/fix for this?

I checked if there is any styling from other plugins messing with this, but there's not.

Tested with current versions of Firefox and Chrome on Win10.

**Comment by gamma** [comment]
Sorry, there is no known fix and the plugin is not in active development currently (due to not being in use ...)
